version: "3.3"

networks:
  auth-service-network:

services:
  backend:
    build: .
    ports:
      - "8010:8010"
    depends_on:
      - mongodb
    networks:
      - auth-service-network

  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - auth-service-network

volumes:
  mongodb_data:
