version: "3.3"

services:
  backend:
    build: .
    ports:
      - "8010:8010"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27018"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
